version: '2.6'
services:
  api:
    container_name: "posts-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: posts-db
      DB_HOST: db
      DB_PORT: 5433

  db:
    container_name: posts-db
    image: postgres:12
    ports:
      - 5435:1433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posts-db
    volumes:
      - pgdata:/var/lib/postgresql/data2

volumes:
  pgdata:
    external: false
