version: '2.6'
services:
  api:
    container_name: "posts-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: posts-db
      DB_HOST: posts-db
      DB_PORT: 5432
      DD_API_KEY: ${DD_API_KEY}
    env_file:
      - .env
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'



  db:
    container_name: posts-db
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posts-db
    volumes:
      - pgdata:/var/lib/postgresql/data2

  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  pgdata:
    external: false
